# Generated by Django 4.0.5 on 2022-06-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_company_name_alter_machine_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='last_working_data',
        ),
        migrations.DeleteModel(
            name='WorkingData',
        ),
    ]
